# Use the official Node.js image as a base
FROM node:22-alpine AS builder

# Set environment variables
ENV NODE_ENV=prod
ENV NEXT_PUBLIC_API_URL=http://demo-vm-todo-app.northeurope.cloudapp.azure.com/api

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --frozen-lockfile

# Copy the rest of the application files
COPY . .

# Build the Next.js application
RUN npm run build

# Use a minimal image for the runtime
FROM node:22-alpine AS runner

# Set the working directory
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
# COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public

# Install only production dependencies
RUN npm install --production

# Set environment variable for production
# ENV NODE_ENV=production

# Expose the port Next.js runs on
EXPOSE 3000

# Start the Next.js application
CMD ["npm", "run", "start"]
