services:
  frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app  # Mounts local frontend folder for development
    #   - /app/node_modules  # Prevents overwriting node_modules for development
    # command: npm run dev  # Run Next.js in development mode
    depends_on:
      - backend
    networks:
      - app-network
    # env_file:
    #   - .env
    # environment:  # Issue: Not loaded, add to Dockerfile instead
    #   - ENV=${ENVIRONMENT}
    #   - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - ENV=${ENVIRONMENT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - DATABASE_URL=${DATABASE_URL}

  postgres:
    image: postgres:latest
    user: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${PGUSER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"      # Expose Nginx on port 80
      - "443:443"    # Expose Nginx on port 443 (for HTTPS)
    volumes:
      - ./${NGINX_CONFIG}:/etc/nginx/nginx.conf  # Load the correct config based on the environment
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx configuration
      # - ./certs:/etc/nginx/certs            # Mount SSL certificates (optional)
      # - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge

volumes:
  db_data:  # Define a volume for PostgreSQL data persistence
