name: Deploy to Azure

on:
  push:
    branches:
      - github-actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure with PAT
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az devops configure --defaults organization=https://dev.azure.com/qianqianqin project=demo
          az login --service-principal -u https://dev.azure.com --tenant ${{ secrets.AZURE_PAT }}

    #   - name: Deploy to Azure VM
    #     run: |
    #       az vm run-command invoke --command-id RunShellScript \
    #         --name <VM_NAME> --resource-group <RESOURCE_GROUP> \
    #         --scripts "cd /your/app/directory && git pull && docker-compose up -d --build"
